remote_theme: SdtElectronics/jekyll-theme-antarctica

title: Leslie's Professional Portfolio
description: "Passionate about crafting functional websites that are a joy to use."

# This section is required by the theme to build the main menu.
navigation:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio
  - title: Blog
    url: /blog

# This section is for social media links.
social:
  - name: github
    url: https://github.com/LeslieMBrock
  - name: linkedin
    url: https://www.linkedin.com/

# This section is for the sidebar widgets.
widgets:
  - id: posts
  - id: categories
  - id: tags
