remote_theme: SdtElectronics/jekyll-theme-antarctica

title: Leslie's Professional Portfolio
description: "Passionate about crafting functional websites that are a joy to use."

# The theme needs this widgets section to know what to display.
widgets:
  - id: posts
  - id: categories
  - id: tags
