
remote_theme: SdtElectronics/jekyll-theme-antarctica

title: Leslie's Professional Portfolio
description: "Passionate about crafting functional websites that are a joy to use."

navigation:
  - title: Home
    url: /
  - title: Portfolio
    url: /portfolio
  - title: Blog
    url: /blog

social:
  - name: github
    url: https://github.com/LeslieMBrock
  - name: linkedin
    url: https://www.linkedin.com/

widgets:
  - id: posts
  - id: categories
  - id: tags

# Make sure these are all defined as arrays
plugins: []
exclude: []
include: []
menu: []
links: []
categories: []
tags: []
